package com.seg.questionnaire;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnLongClickListener;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.TextView;
import android.widget.Toast;

import com.seg.questionnaire.backend.Questionnaire;
import com.seg.questionnaire.backend.json.JSONParser;
import com.seg.questionnaire.backend.question.Question;

/**
 * Class responsible for displaying all questions from a 
 * questionnaire and handling the whole questionnaire.
 * 
 * @author Marek Matejka
 *
 */
public class QuestionActivity extends Activity 
{	
	/**
	 * Defines the current question
	 */
	private int currentQuestion = 0;
		
	/**
	 * Current questionnaire being used.
	 */
	private Questionnaire ques;
	
	/* (non-Javadoc)
	 * @see android.app.Activity#onCreate(android.os.Bundle)
	 */
	@Override
	protected void onCreate(Bundle savedInstanceState) 
	{
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		
		//initialize questionnaire
		ques = new Questionnaire();
		ques.loadDummy();
				
		//load first question
		loadQuestion(ques.getQuestion(currentQuestion));
		
		JSONParser.parse(this);
		
		connect();
		
	}
	
	/**
	 * Responds to click event on 'Next' button.
	 * 
	 * @param v View on which the event happened.
	 */
	public void onClick(View v)
	{
		//take current question and answer
		Question q = ques.getQuestion(currentQuestion);
		Object a = q.getAnswer();
		
		if (a == null) //if no answer
			Toast.makeText(this, "Give me your answer first!", Toast.LENGTH_SHORT).show(); //ask for it
		else
		{
			if (q.hasDependentQuestions(a.toString())) //if there are some dependent questions for a given answer
				ques.addQuestions(q.getDependentQuestions(a.toString()), currentQuestion); //add them to the questionnaire
								
			Toast.makeText(this, "answer = '"+q.getAnswer().toString()+"'", Toast.LENGTH_SHORT).show(); //show the answer
			
			currentQuestion = (currentQuestion+1)%ques.getNumberOfQuestions(); //increase the current question and keep looping
			
			if (currentQuestion == 0) //if first question in new loop
			{
				ques = new Questionnaire(); //create new questionnaire
				ques.loadDummy();
			}
			
			loadQuestion(ques.getQuestion(currentQuestion)); //load next question
		}
	}
	
	/**
	 * Loads a given question and displays it to the user.
	 * 
	 * @param q Question to be loaded and displayed.
	 */
	private void loadQuestion(Question q)
	{	
		updateProgress();
		
		//find the RelativeLayout
		RelativeLayout answer = (RelativeLayout)findViewById(R.id.answer);
		
		//make it empty
		answer.removeAllViews(); 
		
		//add the View generated by the Question
		answer.addView(q.getView(this));
		
		//find the question TextView and set it with question text for the question
		TextView question = (TextView)findViewById(R.id.question);
		question.setText(q.getQuestion());
	}
	
	/**
	 * Updates progress visually to the user.
	 */
	private void updateProgress()
	{
		//find a TextView and set it with current values
		TextView outOf = (TextView) findViewById(R.id.outOf);
		outOf.setText(""+(currentQuestion+1)+"/"+ques.getNumberOfQuestions());
		
		//find a ProgressBar and set it to current value
		ProgressBar p = (ProgressBar) findViewById(R.id.progressBar1);
		p.setMax(ques.getNumberOfQuestions());
		p.setProgress(currentQuestion+1);
	}
	
	/**
	 * Start the tutorial when outOf TextView is clicked.
	 * 
	 * @param v View which was clicked.
	 */
	public void startTutorial(View v)
	{
		startActivity(new Intent(this, TutorialActivity.class));
		onStop();
	}
	
	private void connect()
	{
		TextView v = (TextView)findViewById(R.id.outOf);
		v.setOnLongClickListener(new OnLongClickListener() 
		{
			
			@Override
			public boolean onLongClick(View v) {
				startConnection();
				return true;
			}
		});
	}
	
	private void startConnection()
	{
		startActivity(new Intent(this, ConnectionActivity.class));
		onStop();
	}
}
